# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-04 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_division_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentapp.Division'),
            preserve_default=False,
        ),
    ]
