# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class', to='studentapp.Teacher'),
        ),
    ]
